const sb=window.supabase.createClient(window.DSS_SUPABASE_URL,window.DSS_SUPABASE_KEY);let editing=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function start(){if(window.DSS_SUPABASE_URL.includes('PASTE_'))return;let {data:{session}}=await sb.auth.getSession();if(session)show();}
async function show(){let {data:{session}}=await sb.auth.getSession();if(!session)return;$('#login').hidden=true;$('#panel').hidden=false;$('#logout').hidden=false;loadProducts();loadOrders()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();let {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#loginMsg').textContent=error?error.message:'Sukses';if(!error)show()};$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
async function loadProducts(){let {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error){$('#productsAdmin').textContent=error.message;return}$('#productsAdmin').innerHTML=`<div class="table">${(data||[]).map(p=>`<div class="row"><div><b>${esc(p.name)}</b><small>${esc(p.category||'')} · €${Number(p.price||0).toFixed(2)} · ${p.active?'Aktiv':'Joaktiv'}</small></div><button onclick='edit(${JSON.stringify(p)})'>Ndrysho</button><button onclick='removeP("${p.id}")'>Fshi</button></div>`).join('')}</div>`}
window.edit=p=>{editing=p;let name=prompt('Emri',p.name);if(name===null)return;let price=prompt('Çmimi',p.price);let cat=prompt('Kategoria',p.category||'');let img=prompt('Image URL',p.image_url||'');update({id:p.id,name,price:Number(price),category:cat,image_url:img})};$('#newBtn').onclick=()=>{let name=prompt('Emri i produktit');if(!name)return;let price=Number(prompt('Çmimi','0')||0),cat=prompt('Kategoria','CCTV'),img=prompt('Image URL','');insert({name,price,category:cat,image_url:img})};
async function insert(x){let r=await sb.from('products').insert({...x,active:true});if(r.error)alert(r.error.message);loadProducts()}async function update(x){let r=await sb.from('products').update(x).eq('id',x.id);if(r.error)alert(r.error.message);loadProducts()}window.removeP=async id=>{if(confirm('Fshi produktin?')){let r=await sb.from('products').delete().eq('id',id);if(r.error)alert(r.error.message);loadProducts()}};
async function loadOrders(){let r=await sb.from('orders').select('*').order('created_at',{ascending:false});$('#orders').innerHTML=(r.data||[]).map(o=>`<div class="order"><b>#${esc(o.id)}</b> — ${esc(o.customer_name)} — ${esc(o.phone)} — €${Number(o.total||0).toFixed(2)} — <b>${esc(o.status)}</b></div>`).join('')||'<p>Nuk ka porosi.</p>'}
start();
