const sb = window.supabase.createClient(window.DSS_SUPABASE_URL, window.DSS_SUPABASE_KEY);
let products=[], cart=JSON.parse(localStorage.getItem('dss_cart')||'[]');
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function money(n){return '€'+Number(n||0).toFixed(2)}
function save(){localStorage.setItem('dss_cart',JSON.stringify(cart)); renderCart()}
function renderCart(){ $('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0); $('#cartItems').innerHTML=cart.map((x,i)=>`<div class="cartItem"><div><b>${esc(x.name)}</b><small>${money(x.price)} × ${x.qty}</small></div><div><button onclick="change(${i},-1)">−</button><button onclick="change(${i},1)">+</button></div></div>`).join('')||'<p>Shporta është bosh.</p>'; $('#total').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));}
window.change=(i,d)=>{cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);save()};
function render(){let q=$('#search').value.toLowerCase(), a=products.filter(p=>(p.name||'').toLowerCase().includes(q)||(p.category||'').toLowerCase().includes(q));let s=$('#sort').value;if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);$('#grid').innerHTML=a.map(p=>`<article class="card"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:'DSS'}</div><div class="cat">${esc(p.category||'')}</div><h3>${esc(p.name)}</h3><div class="price">${money(p.sale_price||p.price)}</div><button onclick='add(${JSON.stringify(p)})'>Shto në shportë</button></article>`).join('')||'<p>Nuk u gjetën produkte.</p>'}
window.add=p=>{let x=cart.find(x=>x.id===p.id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:Number(p.sale_price||p.price),qty:1});save();toast('U shtua në shportë')};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
async function load(){if(!window.DSS_SUPABASE_URL.includes('PASTE_')){let {data,error}=await sb.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(!error)products=data||[]} if(!products.length){let r=await fetch('products.json').catch(()=>null);if(r)products=await r.json()} render();renderCart()}
$('#search').oninput=render;$('#sort').onchange=render;$('#cartBtn').onclick=()=>$('#cart').classList.add('open');$('#closeCart').onclick=()=>$('#cart').classList.remove('open');
$('#orderForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Shporta është bosh');let f=new FormData(e.target), total=cart.reduce((a,x)=>a+x.price*x.qty,0);let order={customer_name:f.get('name'),phone:f.get('phone'),address:f.get('address'),total,status:'new'};let {data,error}=await sb.from('orders').insert(order).select().single();if(error)return alert('Porosia nuk u dërgua. Kontrollo lidhjen me Supabase.');let items=cart.map(x=>({order_id:data.id,product_id:x.id,product_name:x.name,quantity:x.qty,unit_price:x.price}));let r=await sb.from('order_items').insert(items);if(r.error)return alert('Porosia u krijua, por artikujt nuk u ruajtën.');let msg=`Përshëndetje DSS, dua të bëj një porosi.%0A%0A${cart.map(x=>`${x.name} x${x.qty} — ${money(x.price*x.qty)}`).join('%0A')}%0A%0ATotal: ${money(total)}%0AEmri: ${f.get('name')}%0ATel: ${f.get('phone')}%0AAdresa: ${f.get('address')}`;window.open('https://wa.me/?text='+msg,'_blank');cart=[];save();e.target.reset();toast('Porosia u regjistrua!')};
load();
